apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argus
spec:
  hosts:
  - "argus-uat.k8s19932be1.boardware.com"
  gateways:
  - istio-gateway/cluster-ingressgateway
  http:
  - route:
    - destination:
        host: argus-svc
        port:
          number: 8080